const S = {
  authPage:     { minHeight:'100vh', display:'flex', alignItems:'center', justifyContent:'center', backgroundColor:'#f0f4f8', fontFamily:'Arial, sans-serif', padding:'20px', boxSizing:'border-box' },
  authCard:     { backgroundColor:'#ffffff', padding:'40px', borderRadius:'12px', width:'100%', maxWidth:'420px', boxShadow:'0 4px 24px rgba(0,0,0,0.08)' },
  authTitle:    { fontSize:'20px', fontWeight:'bold', color:'#17202A', marginBottom:'24px', textAlign:'center' },
  fieldGroup:   { marginBottom:'16px' },
  label:        { display:'block', fontSize:'14px', fontWeight:'bold', color:'#34495e', marginBottom:'6px' },
  input:        { width:'100%', padding:'10px 12px', fontSize:'15px', border:'1.5px solid #d5d8dc', borderRadius:'8px', outline:'none', boxSizing:'border-box', color:'#17202A', backgroundColor:'#ffffff' },
  btn:          { width:'100%', padding:'12px', fontSize:'16px', fontWeight:'bold', backgroundColor:'#1B4F72', color:'#ffffff', border:'none', borderRadius:'8px', cursor:'pointer', marginTop:'8px' },
  btnFlex:      { flex:1, padding:'12px', fontSize:'15px', fontWeight:'bold', backgroundColor:'#1B4F72', color:'#ffffff', border:'none', borderRadius:'8px', cursor:'pointer' },
  btnOff:       { flex:1, padding:'12px', fontSize:'15px', fontWeight:'bold', backgroundColor:'#85929e', color:'#ffffff', border:'none', borderRadius:'8px', cursor:'not-allowed' },
  switchText:   { textAlign:'center', fontSize:'14px', color:'#7f8c8d', marginTop:'20px' },
  switchLink:   { color:'#2E86C1', cursor:'pointer', fontWeight:'bold' },
  logoutBtn:    { padding:'8px 16px', fontSize:'13px', backgroundColor:'transparent', color:'#c0392b', border:'1.5px solid #c0392b', borderRadius:'8px', cursor:'pointer' },
  appBackBtn:   { backgroundColor:'transparent', border:'1px solid rgba(255,255,255,0.4)', color:'#ffffff', borderRadius:'6px', padding:'5px 12px', fontSize:'13px', cursor:'pointer' },
  breadcrumb:   { padding:'0 0 12px 0', fontSize:'13px', backgroundColor:'transparent', border:'none', cursor:'pointer', display:'block' },
  infoBox:      { backgroundColor:'#f8f9fa', borderRadius:'8px', padding:'4px 16px', border:'1.5px solid #eaecee' },
  infoRow:      { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'10px 0' },
  infoLabel:    { fontSize:'14px', color:'#566573' },
  infoValue:    { fontSize:'14px', color:'#17202A' },
  sectionLabel: { fontSize:'12px', fontWeight:'bold', color:'#7f8c8d', textTransform:'uppercase', letterSpacing:'0.5px', marginBottom:'8px', marginTop:'4px' },
  listCard:     { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'12px 16px', backgroundColor:'#f8f9fa', borderRadius:'8px', marginBottom:'8px', border:'1.5px solid #eaecee' },
  listCardTitle:{ fontSize:'15px', fontWeight:'bold', color:'#17202A', margin:'0 0 3px 0' },
  listCardSub:  { fontSize:'13px', color:'#7f8c8d', margin:'0' },
  addBtn:       { padding:'8px 14px', fontSize:'13px', fontWeight:'bold', color:'#ffffff', border:'none', borderRadius:'8px', cursor:'pointer' },
  ghostBtn:     { padding:'8px 14px', fontSize:'13px', fontWeight:'bold', backgroundColor:'transparent', color:'#2E86C1', border:'1.5px solid #2E86C1', borderRadius:'8px', cursor:'pointer' },
  secondaryBtn: { flex:1, padding:'12px', fontSize:'15px', backgroundColor:'transparent', color:'#566573', border:'1.5px solid #d5d8dc', borderRadius:'8px', cursor:'pointer' },
  buttonRow:    { display:'flex', gap:'10px', marginTop:'8px' },
  formBox:      { border:'1.5px solid #eaecee', borderRadius:'10px', padding:'20px', marginBottom:'16px' },
  tab:          { padding:'8px 14px', fontSize:'14px', fontWeight:'bold', backgroundColor:'transparent', color:'#7f8c8d', border:'none', borderBottom:'2px solid transparent', cursor:'pointer', marginBottom:'-2px' },
  dashedBtn:    { width:'100%', padding:'10px', fontSize:'14px', backgroundColor:'transparent', border:'1.5px dashed', borderRadius:'8px', cursor:'pointer' },
  slugWrapper:  { display:'flex', alignItems:'center', border:'1.5px solid #d5d8dc', borderRadius:'8px', overflow:'hidden' },
  slugPrefix:   { padding:'10px 12px', backgroundColor:'#f0f4f8', color:'#7f8c8d', fontSize:'15px', borderRight:'1.5px solid #d5d8dc', whiteSpace:'nowrap' },
  slugInput:    { flex:1, padding:'10px 12px', fontSize:'15px', border:'none', outline:'none', color:'#17202A' },
  stepBox:      { border:'1.5px solid #eaecee', borderRadius:'10px', padding:'18px 20px', marginBottom:'16px' },
  stepNum:      { fontSize:'11px', fontWeight:'bold', color:'#2E86C1', textTransform:'uppercase', letterSpacing:'0.5px', margin:'0 0 4px 0' },
  stepTitle:    { fontSize:'15px', fontWeight:'bold', color:'#17202A', margin:'0 0 6px 0' },
  stepSub:      { fontSize:'13px', color:'#566573', margin:'0 0 12px 0', lineHeight:'1.6' },
  errorBox:     { backgroundColor:'#fadbd8', color:'#c0392b', padding:'12px', borderRadius:'8px', fontSize:'14px' },
}

export default S
